(define-module (gloa store add)
  #:use-module (gloa config)
  #:use-module (gloa store entry)
  #:use-module (gloa store utils)
  #:export (add-to-store))

(define (add-to-store article article-file-path)
  (let* ((result-path (base32-file-name article article-file-path))
         (out (string-append (%default-storage-directory) result-path)))
    (mkdir-p (%default-storage-directory))
    (copy-file article-file-path out)
    (chmod out #o644)))
